FROM ubuntu:19.10
MAINTAINER Vlad Klim 'vladsklim@gmail.com'

# Установка необходимых пакетов для Ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get install -y python3.7 python3.7-dev python3-pip tzdata locales expect git wget unzip

# Установка часового пояса
ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata

# Установка зависимостей для Python3 для сборки
RUN pip3 install six==1.12.0 numpy==1.18.1 wheel==0.32.3 setuptools==41.1.0 mock==4.0.1 future==0.18.2 && \
    pip3 install keras_applications==1.0.8 keras_preprocessing==1.1.0 --no-deps

# Копирование файлов проекта
COPY . /building_tensorflow
WORKDIR /building_tensorflow

# Клонирование репозитория TensorFlow
RUN git clone https://github.com/tensorflow/tensorflow.git

# Копирование скриптов для сборки
RUN cp run_configure_cpu_1.15 tensorflow/run_configure_cpu_1.15 && \
    cp run_configure_gpu_1.15 tensorflow/run_configure_gpu_1.15 && \
    chmod +x tensorflow/run_configure_cpu_1.15 && \
    chmod +x tensorflow/run_configure_gpu_1.15 && \
    chmod +x install_bazel.sh && \
    chmod +x build.sh

# Установка необходимой версии Bazel
RUN ./install_bazel.sh 0.24.1

# Добавления вызова python 3.7 по команде python, без этого сборка будет падать с ошибкой "/usr/bin/env: 'python': No such file or directory"
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2

# Изменение локализации для корректного вывода кириллицы в терминале
RUN locale-gen ru_RU.UTF-8
ENV LANG=ru_RU.UTF-8 \
    LANGUAGE=ru_RU:ru \
    LC_ALL=ru_RU.UTF-8

# Очистка кеша
RUN apt-get -y autoremove && \
    apt-get -y autoclean && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

#CMD ["./build.sh", "-mkl"]
CMD ["./build.sh"]